#!/bin/bash

docker run -ti --rm \
	--cap-add=SYS_PTRACE \
	-e DISPLAY=$DISPLAY \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v $PWD/workspace:/home/develop/workspace \
	-v $(pwd)/workspace:/home/developer/workspace -e USER=$USER  -e USERID=$UID \
	    ivankostov/eclipse-cdt
